#!/usr/bin/env bash

# Inspirted from https://d12frosted.io/posts/2022-04-23-yabai-spaces.html


# load scripting additions
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


###
yabai -m config layout bsp
yabai -m config window_placement second_child
# padding
yabai -m config top_padding   18
yabai -m config bottom_padding 14
yabai -m config left_padding   14
yabai -m config right_padding  14
yabai -m config window_gap     14
# center mouse on window with focus
yabai -m config mouse_follows_focus on
# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize
# when window is dropped in center of another window, swap them (on edges it will split it)
# yabai -m mouse_drop_action swap
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add app="^Logi Options+$" manage=off

borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &

#
# setup spaces
#
for _ in $(yabai -m query --spaces | jq '.[].index | select(. > 6)'); do
  yabai -m space --destroy 7
done

function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}


setup_space 1 wezterm
setup_space 2 code
setup_space 3 web
setup_space 4 github
setup_space 5 slack
setup_space 6 other


# move some apps automatically to specific spaces
yabai -m rule --add app="^WezTerm$" space=^1
yabai -m rule --add app="^Visual Studio Code$" space=^2
yabai -m rule --add app="^Brave Browser$" space=^3
yabai -m rule --add app="^GitHub Desktop$" space=^4
yabai -m rule --add app="^Firefox$" space=^5
yabai -m rule --add app="^Arc$" space=^6
yabai -m rule --add app="^Slack$" space=^7
